import {
  chair1,
  chair2,
  chair3,
  chair4,
  chair5,
  table1,
  table2,
  table3,
  table4,
  table5,
  dine1,
  dine2,
  dine3,
  dine4,
  dine5,
  bed1,
  bed2,
  bed3,
  bed4,
  bed5,
  sofa1,
  sofa2,
  sofa3,
  sofa4,
  sofa5,
  lamp1,
  lamp2,
  lamp3,
  lamp4,
  lamp5,
  storage1,
  storage2,
  storage3,
  storage4,
  storage5,
  garden1,
  garden2,
  garden3,
  garden4,
  garden5,
  kitchen1,
  kitchen2,
  kitchen3,
  kitchen4,
  kitchen5,
} from "../assets/exportProducts";

export const chairs = [
  {
    id: "chair-1",
    title: "Office Chair",
    cost: "$450",
    rating: "4.5",
    photo: chair1,
    content: "Comfortable Chair",
  },
  {
    id: "chair-2",
    title: "White Chair",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: chair2,
    content: "Comfortable Chair",
  },
  {
    id: "chair-3",
    title: "Chair Set",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: chair3,
    content: "Comfortable Chair",
  },
  {
    id: "chair-4",
    title: "Designer Chair",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: chair4,
    content: "Comfortable Chair",
  },
  {
    id: "chair-5",
    title: "Wooden Chair",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: chair5,
    content: "Comfortable Chair",
  },
];

export const tables = [
  {
    id: "table-1",
    title: "Center Table",
    cost: "$450",
    rating: "4.5",
    photo: table1,
    content: "Comfortable Table",
  },
  {
    id: "table-2",
    title: "Glass Table",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: table2,
    content: "Comfortable Table",
  },
  {
    id: "table-3",
    title: "Whitish Table",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: table3,
    content: "Comfortable Table",
  },
  {
    id: "table-4",
    title: "Corner Table",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: table4,
    content: "Comfortable Table",
  },
  {
    id: "table-5",
    title: "Designer Table",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: table5,
    content: "Comfortable Table",
  },
];

export const sofas = [
  {
    id: "sofa-1",
    title: "Drawing Sofa",
    cost: "$450",
    rating: "4.5",
    photo: sofa1,
    content: "Comfortable Sofa",
  },
  {
    id: "sofa-2",
    title: "Lounge Sofa",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: sofa2,
    content: "Comfortable Sofa",
  },
  {
    id: "sofa-3",
    title: "Designer Sofa",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: sofa3,
    content: "Comfortable Sofa",
  },
  {
    id: "sofa-4",
    title: "Wooden Sofa",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: sofa4,
    content: "Comfortable Sofa",
  },
  {
    id: "sofa-5",
    title: "Designer Sofa",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: sofa5,
    content: "Comfortable Sofa",
  },
];

export const beds = [
  {
    id: "bed-1",
    title: "Shielded Bed",
    cost: "$450",
    rating: "4.5",
    photo: bed1,
    content: "Comfortable Bed",
  },
  {
    id: "bed-2",
    title: "Wooden Bed",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: bed2,
    content: "Comfortable Bed",
  },
  {
    id: "bed-3",
    title: "Designer Bed",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: bed3,
    content: "Comfortable Bed",
  },
  {
    id: "bed-4",
    title: "Metal Bed",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: bed4,
    content: "Comfortable Bed",
  },
  {
    id: "bed-5",
    title: "Lavish Bed",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: bed5,
    content: "Comfortable Bed",
  },
];

export const lamps = [
  {
    id: "lamp-1",
    title: "Lighten Lamp",
    cost: "$450",
    rating: "4.5",
    photo: lamp1,
    content: "Comfortable Lamp",
  },
  {
    id: "lamp-2",
    title: "Designer Lamps",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: lamp2,
    content: "Comfortable Lamp",
  },
  {
    id: "lamp-3",
    title: "Blueish Lamp",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: lamp3,
    content: "Comfortable Lamp",
  },
  {
    id: "lamp-4",
    title: "Wooden Lamp",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: lamp4,
    content: "Comfortable Lamp",
  },
  {
    id: "lamp-5",
    title: "Golden Lamp",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: lamp5,
    content: "Comfortable Lamp",
  },
];

export const dines = [
  {
    id: "dine-1",
    title: "8 Seat Dinning",
    cost: "$450",
    rating: "4.5",
    photo: dine1,
    content: "Comfortable Dine In",
  },
  {
    id: "dine-2",
    title: "4 Seat Dinning",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: dine2,
    content: "Comfortable Dine In",
  },
  {
    id: "dine-3",
    title: "6 Seat Dinning",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: dine3,
    content: "Comfortable Dine In",
  },
  {
    id: "dine-4",
    title: "Designer Dinning",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: dine4,
    content: "ComfortabDine In",
  },
  {
    id: "dine-5",
    title: "Wooden Dinning",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: dine5,
    content: "Comfortable Dine In",
  },
];

export const storage = [
  {
    id: "storage-1",
    title: "White Cupboard",
    cost: "$450",
    rating: "4.5",
    photo: storage1,
    content: "Valuable Furniture",
  },
  {
    id: "storage-2",
    title: "Corner Shelf",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: storage2,
    content: "Valuable Furniture",
  },
  {
    id: "storage-3",
    title: "Showcase",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: storage3,
    content: "Valuable Furniture",
  },
  {
    id: "storage-4",
    title: "Corner Cupboard",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: storage4,
    content: "Valuable Furniture",
  },
  {
    id: "storage-5",
    title: "Side Tables",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: storage5,
    content: "Valuable Furniture",
  },
];

export const kitchen = [
  {
    id: "kitchen-1",
    title: "Wood Cupboards",
    cost: "$450",
    rating: "4.5",
    photo: kitchen1,
    content: "The Kitchen Furniture",
  },
  {
    id: "kitchen-2",
    title: "White Set",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: kitchen2,
    content: "The Kitchen Furniture",
  },
  {
    id: "kitchen-3",
    title: "Kitchen Set",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: kitchen3,
    content: "The Kitchen Furniture",
  },
  {
    id: "kitchen-4",
    title: "Corner Shelf",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: kitchen4,
    content: "The Kitchen Furniture",
  },
  {
    id: "kitchen-5",
    title: "Kitchen Chairs",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: kitchen5,
    content: "The Kitchen Furniture",
  },
];

export const garden = [
  {
    id: "garden-1",
    title: "Garden Suite",
    cost: "$450",
    rating: "4.5",
    photo: garden1,
    content: "The Garden Furniture",
  },
  {
    id: "garden-2",
    title: "Grey Sofa Set",
    cost: "$200",
    rating: "4.6",
    reviews: "50 reviews",
    photo: garden2,
    content: "The Garden Furniture",
  },
  {
    id: "garden-3",
    title: "White Suite",
    cost: "$300",
    rating: "4.3",
    reviews: "35 reviews",
    photo: garden3,
    content: "The Garden Furniture",
  },
  {
    id: "garden-4",
    title: "Designer Set",
    cost: "$280",
    rating: "4.7",
    reviews: "20 reviews",
    photo: garden4,
    content: "The Garden Furniture",
  },
  {
    id: "garden-5",
    title: "Black Gardenaria",
    cost: "$500",
    rating: "4.1",
    reviews: "40 reviews",
    photo: garden5,
    content: "The Garden Furniture",
  },
];
